permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css,archive.css,article-list.css,category.css,style.css,tagCloud.css,tags.css]
      scripts : [post.js,category.js,script.js,tagCloud.js,tags.js,toc.js]



title: "A salted fish's blog'"
email: "zxc479773533@gmail.com"
description: "College Student"
github_username:  "zxc479773533"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "rainyalley"




url: "http://zxc479773533.github.io"
imgrepo: "http://zxc479773533.github.io/static/img"